# Generated by Django 5.2.10 on 2026-02-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='FoodHub', help_text='Brand name displayed in navbar and footer', max_length=100)),
                ('logo', models.CharField(default='🍽️', help_text='Logo/emoji displayed in navbar', max_length=10)),
                ('hero_title', models.CharField(help_text='Main title for hero section', max_length=200)),
                ('hero_subtitle', models.TextField(help_text='Subtitle/description for hero section')),
                ('stat_2_value', models.CharField(default='500+', help_text="Value for second stat (e.g., '500+')", max_length=50)),
                ('stat_2_label', models.CharField(default='Menu Items', help_text='Label for second stat', max_length=100)),
                ('stat_3_value', models.CharField(default='1000+', help_text='Value for third stat', max_length=50)),
                ('stat_3_label', models.CharField(default='Happy Customers', help_text='Label for third stat', max_length=100)),
                ('stat_4_value', models.CharField(default='24/7', help_text='Value for fourth stat', max_length=50)),
                ('stat_4_label', models.CharField(default='Service Available', help_text='Label for fourth stat', max_length=100)),
                ('info_banner_icon', models.CharField(default='ℹ️', help_text='Icon/emoji for info banner', max_length=10)),
                ('info_banner_text', models.TextField(help_text='Text content for info banner')),
                ('features_subtitle', models.TextField(default='We bring together the finest restaurants and cutting-edge technology to deliver an exceptional dining experience', help_text='Subtitle for features section')),
                ('feature_1_icon', models.CharField(default='⚡', max_length=10)),
                ('feature_1_title', models.CharField(max_length=100)),
                ('feature_1_description', models.TextField()),
                ('feature_2_icon', models.CharField(default='🚀', max_length=10)),
                ('feature_2_title', models.CharField(max_length=100)),
                ('feature_2_description', models.TextField()),
                ('feature_3_icon', models.CharField(default='💎', max_length=10)),
                ('feature_3_title', models.CharField(max_length=100)),
                ('feature_3_description', models.TextField()),
                ('about_title', models.CharField(default='About Our Platform', max_length=200)),
                ('about_description', models.TextField()),
                ('about_description_2', models.TextField(blank=True)),
                ('highlight_1', models.CharField(default='Trusted by Top Restaurants', max_length=100)),
                ('highlight_2', models.CharField(default='Real-time Order Tracking', max_length=100)),
                ('highlight_3', models.CharField(default='Secure Payments', max_length=100)),
                ('highlight_4', models.CharField(default='24/7 Customer Support', max_length=100)),
                ('cta_title', models.CharField(help_text='Call-to-action section title', max_length=200)),
                ('cta_description', models.TextField(help_text='CTA section description')),
                ('cta_button_text', models.CharField(default='Start Ordering Now', help_text='Text for CTA button', max_length=100)),
                ('footer_tagline', models.TextField(default='Your one-stop platform for discovering and ordering from the best restaurants in town.', help_text='Tagline displayed in footer')),
                ('footer_text', models.TextField(default='© 2024 FoodHub. All rights reserved.', help_text='Copyright text for footer')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this landing page is currently active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
            },
        ),
    ]
