# Generated by Django 5.2.10 on 2026-02-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('pricing', 'Pricing & Subscription'), ('about', 'About Us'), ('contact', 'Contact Us'), ('faq', 'FAQ')], help_text='Type of content page', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Page title', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug', unique=True)),
                ('content', models.TextField(help_text='Full HTML or plain text content')),
                ('description', models.TextField(blank=True, help_text='Short description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Page',
                'verbose_name_plural': 'Content Pages',
                'ordering': ['content_type'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('quick_links', 'Quick Links'), ('for_restaurants', 'For Restaurants'), ('support', 'Support'), ('company', 'Company'), ('legal', 'Legal')], help_text='Footer section', max_length=20)),
                ('title', models.CharField(help_text='Link text/title', max_length=100)),
                ('url', models.CharField(help_text="URL or content page slug (e.g., '#privacy' or 'https://example.com')", max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['section', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('custom', 'Custom')], help_text='Social media platform', max_length=20)),
                ('icon', models.CharField(help_text='Icon/emoji for the social link', max_length=10)),
                ('url', models.URLField(help_text='Link URL')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_section_company_title',
            field=models.CharField(default='Company', help_text='Title for Company section', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_section_for_restaurants_title',
            field=models.CharField(default='For Restaurants', help_text='Title for For Restaurants section', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_section_legal_title',
            field=models.CharField(default='Legal', help_text='Title for Legal section', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_section_quick_links_title',
            field=models.CharField(default='Quick Links', help_text='Title for Quick Links section', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_section_support_title',
            field=models.CharField(default='Support', help_text='Title for Support section', max_length=100),
        ),
    ]
