# Generated by Django 5.2.10 on 2026-02-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_contentpage_footerlink_socialmedialink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Icon/emoji for the app card', max_length=10)),
                ('title', models.CharField(help_text='App name/title', max_length=100)),
                ('description', models.TextField(help_text='App description')),
                ('ios_link', models.URLField(blank=True, help_text='iOS app download link')),
                ('android_link', models.URLField(blank=True, help_text='Android app download link')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Card',
                'verbose_name_plural': 'App Cards',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='landingpage',
            name='app_section_description',
            field=models.TextField(default='Manage your restaurant and orders on the go with our powerful mobile applications', help_text='Description for app section'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='app_section_title',
            field=models.CharField(default='📱 Download Our Apps', help_text='Title for app section', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='restaurants_section_subtitle',
            field=models.TextField(default='Discover amazing restaurants and order your favorite dishes with just a few clicks', help_text='Subtitle for restaurants section'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='restaurants_section_tag',
            field=models.CharField(default='Our Partners', help_text='Tag for restaurants section', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='restaurants_section_title',
            field=models.CharField(default='🍽️ Featured Restaurants', help_text='Title for restaurants section', max_length=200),
        ),
    ]
