# Generated by Django 5.2.10 on 2026-02-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_appcard_landingpage_app_section_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='about_image',
            field=models.ImageField(blank=True, help_text='About section image', null=True, upload_to='landing_page/'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='features_title',
            field=models.CharField(default='✨ Experience the Best', help_text='Title for features section', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_cta_link',
            field=models.CharField(default='#restaurants', help_text='CTA button link (use # for sections, http for external)', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_cta_text',
            field=models.CharField(default='Browse Restaurants', help_text='Call-to-action button text in hero', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero section background image', null=True, upload_to='landing_page/'),
        ),
    ]
