# Generated by Django 5.2.10 on 2026-02-02 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_landingpage_about_image_landingpage_features_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcard',
            name='landing_page',
            field=models.ForeignKey(blank=True, help_text='Associated landing page (leave blank for global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_cards', to='customer.landingpage'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='landing_page',
            field=models.ForeignKey(blank=True, help_text='Associated landing page (leave blank for global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='customer.landingpage'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='landing_page',
            field=models.ForeignKey(blank=True, help_text='Associated landing page (leave blank for global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='customer.landingpage'),
        ),
    ]
