# Generated by Django 5.2.10 on 2026-02-02 17:53

import core.services.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_appcard_landing_page_footerlink_landing_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='about_image',
            field=models.ImageField(blank=True, help_text='About section image (800x600 recommended)', null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to='bhansa_ghar_landing_page/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero section background image (1920x1080 recommended)', null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to='bhansa_ghar_landing_page/'),
        ),
    ]
