# Generated by Django 5.2.10 on 2026-02-03 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_landingpage_about_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who updated this landing page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
