# Generated by Django 5.2.9 on 2026-02-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_add_updated_by_to_landing_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcard',
            name='icon',
            field=models.TextField(help_text='Icon/emoji or SVG code for the app card'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='feature_1_icon',
            field=models.TextField(default='⚡'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='feature_2_icon',
            field=models.TextField(default='🚀'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='feature_3_icon',
            field=models.TextField(default='💎'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='info_banner_icon',
            field=models.TextField(default='ℹ️', help_text='Icon/emoji or SVG code for info banner'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='logo',
            field=models.TextField(default='🍽️', help_text='Logo/emoji or SVG code displayed in navbar'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='icon',
            field=models.TextField(help_text='Icon/emoji or SVG code for the social link'),
        ),
    ]
