# Generated by Django 5.2.10 on 2026-02-03 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_appcard_icon_alter_landingpage_feature_1_icon_and_more'),
        ('restaurants', '0018_restaurantgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Name of the person who gave the testimonial', max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating out of 5 stars')),
                ('text', models.TextField(help_text='Testimonial content')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this testimonial')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(help_text='Restaurant this testimonial belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
