# Generated by Django 5.2.10 on 2026-02-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_testimonial'),
        ('restaurants', '0018_restaurantgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Associated restaurant (leave blank for global or landing page specific)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='restaurants.restaurant'),
        ),
    ]
