# Generated by Django 5.2.10 on 2026-02-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_socialmediaplatform_and_migrate_platform_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcard',
            options={'ordering': ['order'], 'verbose_name': 'App Card', 'verbose_name_plural': 'App Cards'},
        ),
        migrations.AlterModelOptions(
            name='contentpage',
            options={'ordering': ['title'], 'verbose_name': 'Content Page', 'verbose_name_plural': 'Content Pages'},
        ),
        migrations.RemoveField(
            model_name='appcard',
            name='landing_page',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='footerlink',
            name='landing_page',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='app_section_description',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='app_section_title',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='features_title',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='hero_cta_text',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='restaurants_section_subtitle',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='restaurants_section_tag',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='restaurants_section_title',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='socialmediaplatform',
            name='color',
        ),
        migrations.AlterField(
            model_name='appcard',
            name='icon',
            field=models.CharField(help_text='Icon/emoji for the app card', max_length=10),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=models.TextField(help_text='Page content (supports HTML)'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this page is published'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='slug',
            field=models.SlugField(help_text='URL slug for the page', unique=True),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='section',
            field=models.CharField(choices=[('quick_links', 'Quick Links'), ('company', 'Company'), ('for_restaurants', 'For Restaurants'), ('legal', 'Legal'), ('support', 'Support')], help_text='Footer section this link belongs to', max_length=20),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='about_image',
            field=models.TextField(blank=True, help_text='About section image URL or SVG', null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='feature_1_icon',
            field=models.CharField(default='⚡', max_length=10),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='feature_2_icon',
            field=models.CharField(default='🚀', max_length=10),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='feature_3_icon',
            field=models.CharField(default='💎', max_length=10),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_image',
            field=models.TextField(blank=True, help_text='Hero section image URL or SVG', null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='highlight_1',
            field=models.CharField(default='Trusted by Top Restaurants', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='highlight_2',
            field=models.CharField(default='Real-time Order Tracking', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='highlight_3',
            field=models.CharField(default='Secure Payments', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='highlight_4',
            field=models.CharField(default='24/7 Customer Support', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='info_banner_icon',
            field=models.CharField(default='ℹ️', help_text='Icon/emoji for info banner', max_length=10),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='logo',
            field=models.CharField(default='🍽️', help_text='Logo/emoji displayed in navbar', max_length=10),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='url',
            field=models.URLField(help_text='Link URL or contact info for this platform'),
        ),
        migrations.AlterField(
            model_name='socialmediaplatform',
            name='icon',
            field=models.CharField(help_text="Icon (emoji, font-awesome class, SVG, or PNG/SVG URL link). E.g., '👍' or 'fab fa-facebook-f' or 'https://example.com/icon.svg'", max_length=500),
        ),
    ]
