# Generated by Django 5.2.10 on 2026-02-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_appcard_options_alter_contentpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaplatform',
            name='icon',
            field=models.CharField(help_text="Icon (emoji, font-awesome class, SVG, or PNG/SVG URL link). E.g., '👍' or 'fab fa-facebook-f' or '<svg>...</svg>' or 'https://example.com/icon.svg'", max_length=5000),
        ),
    ]
