# Generated by Django 5.2.10 on 2026-02-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_socialmediaplatform_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='app_section_description',
            field=models.TextField(default='Get the best experience with our mobile apps', help_text='Description for app download section'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='app_section_title',
            field=models.CharField(default='Download Our Apps', help_text='Title for app download section', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='features_title',
            field=models.CharField(default='Why Choose Us', help_text='Title for features section', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='restaurants_section_subtitle',
            field=models.TextField(default='Discover amazing food from our partner restaurants', help_text='Subtitle for restaurants section'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='restaurants_section_tag',
            field=models.CharField(default='Explore', help_text='Tag/label for restaurants section', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='restaurants_section_title',
            field=models.CharField(default='Partner Restaurants', help_text='Title for restaurants section', max_length=200),
        ),
    ]
