# Generated by Django 5.2.9 on 2026-02-04 15:41

import core.services.storage
import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_landingpage_app_section_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcard',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Icon image file (takes precedence over SVG and emoji)', max_length=500, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to='bhansa_ghar/landing_page/app_card_icons/'),
        ),
        migrations.AddField(
            model_name='appcard',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG code for app icon (takes precedence over emoji icon)', null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='feature_1_icon_image',
            field=models.ImageField(blank=True, help_text='Feature 1 icon image (optional, takes precedence over emoji)', max_length=500, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to=customer.models.landing_page_feature_1_icon_upload_to),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='feature_2_icon_image',
            field=models.ImageField(blank=True, help_text='Feature 2 icon image (optional, takes precedence over emoji)', max_length=500, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to=customer.models.landing_page_feature_2_icon_upload_to),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='feature_3_icon_image',
            field=models.ImageField(blank=True, help_text='Feature 3 icon image (optional, takes precedence over emoji)', max_length=500, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to=customer.models.landing_page_feature_3_icon_upload_to),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='info_banner_image',
            field=models.ImageField(blank=True, help_text='Info banner background image (optional)', max_length=500, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to=customer.models.landing_page_info_banner_upload_to),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='navbar_logo_image',
            field=models.ImageField(blank=True, help_text='Logo image for navbar (optional, displayed before brand name)', max_length=500, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to=customer.models.landing_page_navbar_logo_upload_to),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero section background image', max_length=500, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to=customer.models.landing_page_hero_image_upload_to),
        ),
    ]
