# Generated by Django 5.2.9 on 2026-02-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_appcard_icon_image_appcard_icon_svg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='hero_cta_link',
            field=models.CharField(blank=True, default='#restaurants', help_text='Link for hero CTA button (e.g., #restaurants, /menu, https://example.com)', max_length=500),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_cta_text',
            field=models.CharField(default='Browse Restaurants', help_text='Text for the hero section CTA button', max_length=100),
        ),
    ]
