# Generated by Django 5.2.9 on 2026-01-23 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderServeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_status_before', models.CharField(max_length=20)),
                ('served_items', models.JSONField()),
                ('waiter_notes', models.TextField(blank=True)),
                ('served_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serve_logs', to='orders.order')),
            ],
        ),
    ]
