# Generated by Django 5.2.9 on 2026-02-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_empty'),
    ]

    operations = [
        # RunSQL with conditional handling for resolved_at column
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='orders_orderbargain' AND column_name='resolved_at'
                ) THEN
                    ALTER TABLE orders_orderbargain RENAME COLUMN resolved_at TO answered_at;
                END IF;
            END $$;
            """,
            reverse_sql="SELECT 1;",  # No-op reverse for safety
            state_operations=[
                migrations.RenameField(
                    model_name='orderbargain',
                    old_name='resolved_at',
                    new_name='answered_at',
                ),
            ]
        ),
        # Conditional removal of items field from Order
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='orders_order' AND column_name='items_id'
                ) THEN
                    ALTER TABLE orders_order DROP COLUMN items_id;
                END IF;
            END $$;
            """,
            reverse_sql="SELECT 1;",
            state_operations=[
                migrations.RemoveField(
                    model_name='order',
                    name='items',
                ),
            ]
        ),
        # Conditional removal of customer_qty field from OrderBargain
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='orders_orderbargain' AND column_name='customer_qty'
                ) THEN
                    ALTER TABLE orders_orderbargain DROP COLUMN customer_qty;
                END IF;
            END $$;
            """,
            reverse_sql="SELECT 1;",
            state_operations=[
                migrations.RemoveField(
                    model_name='orderbargain',
                    name='customer_qty',
                ),
            ]
        ),
        # Conditional removal of item_id field from OrderBargain
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='orders_orderbargain' AND column_name='item_id'
                ) THEN
                    ALTER TABLE orders_orderbargain DROP COLUMN item_id;
                END IF;
            END $$;
            """,
            reverse_sql="SELECT 1;",
            state_operations=[
                migrations.RemoveField(
                    model_name='orderbargain',
                    name='item_id',
                ),
            ]
        ),
        # Conditional removal of kitchen_message field from OrderBargain
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='orders_orderbargain' AND column_name='kitchen_message'
                ) THEN
                    ALTER TABLE orders_orderbargain DROP COLUMN kitchen_message;
                END IF;
            END $$;
            """,
            reverse_sql="SELECT 1;",
            state_operations=[
                migrations.RemoveField(
                    model_name='orderbargain',
                    name='kitchen_message',
                ),
            ]
        ),
        # Conditional removal of kitchen_qty field from OrderBargain
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='orders_orderbargain' AND column_name='kitchen_qty'
                ) THEN
                    ALTER TABLE orders_orderbargain DROP COLUMN kitchen_qty;
                END IF;
            END $$;
            """,
            reverse_sql="SELECT 1;",
            state_operations=[
                migrations.RemoveField(
                    model_name='orderbargain',
                    name='kitchen_qty',
                ),
            ]
        ),
        # Conditional removal of status field from OrderBargain
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='orders_orderbargain' AND column_name='status'
                ) THEN
                    ALTER TABLE orders_orderbargain DROP COLUMN status;
                END IF;
            END $$;
            """,
            reverse_sql="SELECT 1;",
            state_operations=[
                migrations.RemoveField(
                    model_name='orderbargain',
                    name='status',
                ),
            ]
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderbargain',
            name='accepted_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderbargain',
            name='action_type',
            field=models.CharField(choices=[('quantity_adjustment', 'Quantity Adjustment'), ('availability', 'Availability Issue'), ('substitution', 'Substitution Request')], default='quantity_adjustment', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbargain',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderbargain',
            name='customer_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderbargain',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderbargain',
            name='order_item_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderbargain',
            name='requested_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderbargain',
            name='staff_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='orderbargain',
            name='customer_response',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
