# Generated by Django 5.2.10 on 2026-01-31 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0016_table_last_served_table_notes_alter_table_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_prep_time_seconds', models.IntegerField(blank=True, null=True)),
                ('min_prep_time_seconds', models.IntegerField(blank=True, null=True)),
                ('max_prep_time_seconds', models.IntegerField(blank=True, null=True)),
                ('tables_turnover', models.FloatField(default=0)),
                ('unique_tables_served', models.IntegerField(default=0)),
                ('bargain_orders_count', models.IntegerField(default=0)),
                ('bargain_success_rate', models.FloatField(default=0)),
                ('pending_orders', models.IntegerField(default=0)),
                ('preparing_orders', models.IntegerField(default=0)),
                ('ready_orders', models.IntegerField(default=0)),
                ('served_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('avg_serve_time_seconds', models.IntegerField(blank=True, null=True)),
                ('peak_hour', models.IntegerField(blank=True, null=True)),
                ('peak_hour_orders', models.IntegerField(default=0)),
                ('active_kitchen_staff', models.IntegerField(default=0)),
                ('active_waiters', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['restaurant', 'date'], name='analytics_d_restaur_77e960_idx')],
                'unique_together': {('restaurant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField(choices=[(0, '00:00'), (1, '01:00'), (2, '02:00'), (3, '03:00'), (4, '04:00'), (5, '05:00'), (6, '06:00'), (7, '07:00'), (8, '08:00'), (9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00')])),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_prep_time_seconds', models.IntegerField(blank=True, null=True)),
                ('bargain_orders', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_analytics', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-date', '-hour'],
                'indexes': [models.Index(fields=['restaurant', 'date', 'hour'], name='analytics_h_restaur_fefa4d_idx')],
                'unique_together': {('restaurant', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='TopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rank', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_items', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-date', 'rank'],
                'indexes': [models.Index(fields=['restaurant', 'date', 'rank'], name='analytics_t_restaur_8512a6_idx')],
                'unique_together': {('restaurant', 'date', 'item_id')},
            },
        ),
    ]
