# Generated by Django 5.2.10 on 2026-01-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='operating_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tables_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
