# Generated by Django 5.2.10 on 2026-01-09 16:27

import django.db.models.deletion
from django.db import migrations, models


def create_restaurant_types(apps, schema_editor):
    RestaurantType = apps.get_model('restaurants', 'RestaurantType')
    # Create default restaurant types
    types_data = [
        {'name': 'restaurant', 'display_name': 'Restaurant'},
        {'name': 'cafe', 'display_name': 'Cafe'},
        {'name': 'hotel', 'display_name': 'Hotel'},
        {'name': 'bar', 'display_name': 'Bar'},
        {'name': 'fastfood', 'display_name': 'Fast Food'},
    ]
    for type_data in types_data:
        RestaurantType.objects.get_or_create(
            name=type_data['name'],
            defaults={'display_name': type_data['display_name']}
        )


def migrate_restaurant_types(apps, schema_editor):
    # Since the field is still CharField during this migration,
    # we need to update the database directly with raw SQL
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # First, create a temporary mapping table or update directly
        # Update restaurants set type_new_id = (select id from restaurants_restauranttype where name = lower(restaurants.type))
        cursor.execute("""
            UPDATE restaurants_restaurant
            SET type_new_id = rt.id
            FROM restaurants_restauranttype rt
            WHERE LOWER(restaurants_restaurant.type) = rt.name
        """)
        # Then set type to NULL or drop the column later, but AlterField will handle it


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_description_restaurant_operating_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(create_restaurant_types, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='restaurant',
            name='type_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restauranttype'),
        ),
        migrations.RunPython(migrate_restaurant_types, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='restaurant',
            name='type',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='type_new',
            new_name='type',
        ),
    ]
