# Generated by Django 5.2.10 on 2026-01-12 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_category_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='stock',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
