# Generated by Django 5.2.10 on 2026-01-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_rename_price_menuitem_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
