# Generated by Django 5.2.10 on 2026-01-12 05:50

import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_menuitem_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurants.models.menu_image_upload_to),
        ),
    ]
