# Generated by Django 5.2.9 on 2026-01-13 06:55

import core.services.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_menuitem_image_alter_menuitem_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.PositiveIntegerField()),
                ('qr_code', models.ImageField(blank=True, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to='table_qr_codes/')),
                ('qr_code_data', models.CharField(max_length=500, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['table_number'],
                'unique_together': {('restaurant', 'table_number')},
            },
        ),
    ]
