# Generated by Django 5.2.10 on 2026-01-16 12:09

import core.services.storage
import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to=restaurants.models.qr_code_upload_to),
        ),
    ]
