# Generated by Django 5.2.10 on 2026-01-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_table_qr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number']},
        ),
        migrations.RenameField(
            model_name='table',
            old_name='table_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='qr_code',
            new_name='qr_code_image',
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'number')},
        ),
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='table',
            name='qr_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'Available 🟢'), ('occupied', 'Occupied 🟡'), ('ordering', 'Ordering 🟠'), ('preparing', 'Preparing 🔴'), ('ready', 'Ready 🟢'), ('served', 'Served ✅'), ('dirty', 'Dirty 🟠')], default='available', max_length=20),
        ),
        migrations.RemoveField(
            model_name='table',
            name='qr_code_data',
        ),
    ]
