# Generated by Django 5.2.9 on 2026-01-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_staffinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinvite',
            name='qr_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
