# Generated by Django 5.2.9 on 2026-01-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_alter_staffinvite_qr_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qr_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
