# Generated by Django 5.2.9 on 2026-01-20 06:41

import core.services.storage
import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_alter_table_qr_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinvite',
            name='qr_code_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to=restaurants.models.staff_invite_qr_upload_to),
        ),
        migrations.AlterField(
            model_name='table',
            name='qr_code_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to=restaurants.models.qr_code_upload_to),
        ),
    ]
