# Generated by Django 5.2.9 on 2026-01-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_alter_staffinvite_qr_code_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='last_served',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', '🟢 Available'), ('occupied', '🟡 Occupied'), ('ready', '🔵 Ready'), ('serving', '🟠 Serving'), ('dirty', '🔴 Dirty')], default='available', max_length=20),
        ),
    ]
