# Generated by Django 5.2.10 on 2026-02-02 04:45

import core.services.storage
from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    """Generate unique slugs for existing restaurants"""
    Restaurant = apps.get_model('restaurants', 'Restaurant')
    for restaurant in Restaurant.objects.all():
        if not restaurant.slug:
            # Generate slug from restaurant name or id
            base_slug = slugify(restaurant.name) or f'restaurant-{restaurant.id}'
            restaurant.slug = base_slug
            restaurant.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_table_last_served_table_notes_alter_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='about',
            field=models.TextField(blank=True, help_text='About the restaurant for public website'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to='bhansa_ghar/hero/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(db_index=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(generate_slugs),
    ]
