# Generated by Django 5.2.10 on 2026-02-02 05:37

import core.services.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_add_slug_and_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=500, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to='bhansa_ghar/gallery/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
