// Mocks generated by Mockito 5.4.4 from annotations
// in local_cafehub/test/stock_logic_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bhansa_ghar/offline/ui/feature/categories/data/models/category.dart'
    as _i6;
import 'package:bhansa_ghar/offline/ui/feature/categories/domain/repositories/category_repository.dart'
    as _i5;
import 'package:bhansa_ghar/offline/ui/feature/menus/data/menu_item.dart' as _i4;
import 'package:bhansa_ghar/offline/ui/feature/menus/domain/menu_repository.dart'
    as _i2;
import 'package:bhansa_ghar/offline/ui/feature/orders/data/models/order_item.dart'
    as _i10;
import 'package:bhansa_ghar/offline/ui/feature/orders/domain/repositories/order_repository.dart'
    as _i9;
import 'package:bhansa_ghar/offline/ui/feature/tables/data/models/table.dart' as _i8;
import 'package:bhansa_ghar/offline/ui/feature/tables/domain/repositories/table_repository.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MenuRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMenuRepository extends _i1.Mock implements _i2.MenuRepository {
  MockMenuRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MenuItem>> getMenu() => (super.noSuchMethod(
        Invocation.method(
          #getMenu,
          [],
        ),
        returnValue: _i3.Future<List<_i4.MenuItem>>.value(<_i4.MenuItem>[]),
      ) as _i3.Future<List<_i4.MenuItem>>);

  @override
  _i3.Future<void> addMenuItem(_i4.MenuItem? item) => (super.noSuchMethod(
        Invocation.method(
          #addMenuItem,
          [item],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateMenuItem(_i4.MenuItem? item) => (super.noSuchMethod(
        Invocation.method(
          #updateMenuItem,
          [item],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMenuItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMenuItem,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> importMenuItems(List<_i4.MenuItem>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #importMenuItems,
          [items],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateStock(
    String? itemId,
    int? quantityChange,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStock,
          [
            itemId,
            quantityChange,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i5.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.Category>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i3.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i3.Future<List<_i6.Category>>);

  @override
  _i3.Future<void> addCategory(_i6.Category? category) => (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [category],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCategory(_i6.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> importCategories(List<_i6.Category>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #importCategories,
          [categories],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [TableRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTableRepository extends _i1.Mock implements _i7.TableRepository {
  MockTableRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i8.TableModel>> getTables() => (super.noSuchMethod(
        Invocation.method(
          #getTables,
          [],
        ),
        returnValue: _i3.Future<List<_i8.TableModel>>.value(<_i8.TableModel>[]),
      ) as _i3.Future<List<_i8.TableModel>>);

  @override
  _i3.Future<void> addTable(_i8.TableModel? table) => (super.noSuchMethod(
        Invocation.method(
          #addTable,
          [table],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateTable(_i8.TableModel? table) => (super.noSuchMethod(
        Invocation.method(
          #updateTable,
          [table],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTable(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTable,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setNumberOfTables(int? count) => (super.noSuchMethod(
        Invocation.method(
          #setNumberOfTables,
          [count],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getTableCount() => (super.noSuchMethod(
        Invocation.method(
          #getTableCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i9.OrderRepository {
  MockOrderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i10.Order> get onOrderAdded => (super.noSuchMethod(
        Invocation.getter(#onOrderAdded),
        returnValue: _i3.Stream<_i10.Order>.empty(),
      ) as _i3.Stream<_i10.Order>);

  @override
  _i3.Future<List<_i10.Order>> getOrders() => (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
        ),
        returnValue: _i3.Future<List<_i10.Order>>.value(<_i10.Order>[]),
      ) as _i3.Future<List<_i10.Order>>);

  @override
  _i3.Future<_i10.Order?> getOrder(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [id],
        ),
        returnValue: _i3.Future<_i10.Order?>.value(),
      ) as _i3.Future<_i10.Order?>);

  @override
  _i3.Future<void> addOrder(_i10.Order? order) => (super.noSuchMethod(
        Invocation.method(
          #addOrder,
          [order],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateOrderStatus(
    String? orderId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderStatus,
          [
            orderId,
            status,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllOrders() => (super.noSuchMethod(
        Invocation.method(
          #clearAllOrders,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> negotiateOrder(
    String? orderId,
    List<Map<String, dynamic>>? items,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #negotiateOrder,
          [
            orderId,
            items,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
