// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'website_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

WebsiteData _$WebsiteDataFromJson(Map<String, dynamic> json) => WebsiteData(
  id: json['id'] as String,
  websiteTitle: json['website_title'] as String?,
  websiteDescription: json['website_description'] as String?,
  websiteKeywords: json['website_keywords'] as String?,
  logo: json['logo'] as String?,
  favicon: json['favicon'] as String?,
  primaryColor: json['primary_color'] as String? ?? '#FF6B6B',
  secondaryColor: json['secondary_color'] as String? ?? '#4ECDC4',
  facebookUrl: json['facebook_url'] as String?,
  instagramUrl: json['instagram_url'] as String?,
  twitterUrl: json['twitter_url'] as String?,
  whatsappNumber: json['whatsapp_number'] as String?,
  contactEmail: json['contact_email'] as String?,
  contactPhone: json['contact_phone'] as String?,
  contactWhatsapp: json['contact_whatsapp'] as String?,
  heroTitle: json['hero_title'] as String?,
  heroSubtitle: json['hero_subtitle'] as String?,
  heroCTAButtonText: json['hero_cta_button_text'] as String? ?? 'Order Now',
  heroCTAButtonLink: json['hero_cta_button_link'] as String?,
  aboutTitle: json['about_title'] as String? ?? 'About Us',
  aboutContent: json['about_content'] as String?,
  aboutImage: json['about_image'] as String?,
  feature1Title: json['feature_1_title'] as String?,
  feature1Description: json['feature_1_description'] as String?,
  feature1Icon: json['feature_1_icon'] as String?,
  feature2Title: json['feature_2_title'] as String?,
  feature2Description: json['feature_2_description'] as String?,
  feature2Icon: json['feature_2_icon'] as String?,
  feature3Title: json['feature_3_title'] as String?,
  feature3Description: json['feature_3_description'] as String?,
  feature3Icon: json['feature_3_icon'] as String?,
  enableNewsletter: json['enable_newsletter'] as bool? ?? true,
  enableContactForm: json['enable_contact_form'] as bool? ?? true,
  footerText: json['footer_text'] as String?,
  isActive: json['is_active'] as bool? ?? true,
  showMenuOnline: json['show_menu_online'] as bool? ?? true,
  showReservationsOnline: json['show_reservations_online'] as bool? ?? true,
  createdAt: DateTime.parse(json['created_at'] as String),
  updatedAt: DateTime.parse(json['updated_at'] as String),
);

Map<String, dynamic> _$WebsiteDataToJson(WebsiteData instance) =>
    <String, dynamic>{
      'id': instance.id,
      'website_title': instance.websiteTitle,
      'website_description': instance.websiteDescription,
      'website_keywords': instance.websiteKeywords,
      'logo': instance.logo,
      'favicon': instance.favicon,
      'primary_color': instance.primaryColor,
      'secondary_color': instance.secondaryColor,
      'facebook_url': instance.facebookUrl,
      'instagram_url': instance.instagramUrl,
      'twitter_url': instance.twitterUrl,
      'whatsapp_number': instance.whatsappNumber,
      'contact_email': instance.contactEmail,
      'contact_phone': instance.contactPhone,
      'contact_whatsapp': instance.contactWhatsapp,
      'hero_title': instance.heroTitle,
      'hero_subtitle': instance.heroSubtitle,
      'hero_cta_button_text': instance.heroCTAButtonText,
      'hero_cta_button_link': instance.heroCTAButtonLink,
      'about_title': instance.aboutTitle,
      'about_content': instance.aboutContent,
      'about_image': instance.aboutImage,
      'feature_1_title': instance.feature1Title,
      'feature_1_description': instance.feature1Description,
      'feature_1_icon': instance.feature1Icon,
      'feature_2_title': instance.feature2Title,
      'feature_2_description': instance.feature2Description,
      'feature_2_icon': instance.feature2Icon,
      'feature_3_title': instance.feature3Title,
      'feature_3_description': instance.feature3Description,
      'feature_3_icon': instance.feature3Icon,
      'enable_newsletter': instance.enableNewsletter,
      'enable_contact_form': instance.enableContactForm,
      'footer_text': instance.footerText,
      'is_active': instance.isActive,
      'show_menu_online': instance.showMenuOnline,
      'show_reservations_online': instance.showReservationsOnline,
      'created_at': instance.createdAt.toIso8601String(),
      'updated_at': instance.updatedAt.toIso8601String(),
    };
