# Generated by Django 5.2.10 on 2026-01-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
