# Generated by Django 5.2.9 on 2026-01-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_mode_and_registration_fields'),
        ('core', '0004_user_last_code_sent_at'),
    ]

    operations = [
    ]
