# Generated by Django 5.2.10 on 2026-01-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260110_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
