# Generated by Django 5.2.9 on 2026-01-29 05:15

import core.models
import core.services.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to=core.models.user_avatar_upload_to),
        ),
    ]
