# Generated by Django 5.2.9 on 2026-01-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activitylog'),
        ('core', '0011_alter_user_avatar'),
    ]

    operations = [
    ]
