# Generated by Django 5.2.10 on 2026-01-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_0007_activitylog_0011_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_user_id_599332_idx',
            old_name='core_activi_user_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_user_id_fc76d8_idx',
            old_name='core_activi_user_id_activity_type_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_restaur_e74fee_idx',
            old_name='core_activi_restaurant_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_created_5c6490_idx',
            old_name='core_activi_created_at_idx',
        ),
    ]
