# Generated by Django 5.2.9 on 2026-02-02 09:23

import core.services.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_core_activi_user_id_created_at_idx_core_activi_user_id_599332_idx_and_more'),
        ('restaurants', '0018_restaurantgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_title', models.CharField(blank=True, help_text='Website title for SEO', max_length=200)),
                ('website_description', models.TextField(blank=True, help_text='Website meta description')),
                ('website_keywords', models.CharField(blank=True, help_text='SEO keywords separated by commas', max_length=500)),
                ('logo', models.ImageField(blank=True, max_length=500, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to='bhansa_ghar/website/logos/')),
                ('favicon', models.ImageField(blank=True, max_length=500, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to='bhansa_ghar/website/favicons/')),
                ('primary_color', models.CharField(default='#FF6B6B', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#4ECDC4', help_text='Secondary brand color (hex)', max_length=7)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=200)),
                ('hero_cta_button_text', models.CharField(blank=True, default='Order Now', max_length=50)),
                ('hero_cta_button_link', models.URLField(blank=True, null=True)),
                ('about_title', models.CharField(blank=True, default='About Us', max_length=200)),
                ('about_content', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, max_length=500, null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to='bhansa_ghar/website/about/')),
                ('feature_1_title', models.CharField(blank=True, max_length=100)),
                ('feature_1_description', models.TextField(blank=True)),
                ('feature_1_icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('feature_2_title', models.CharField(blank=True, max_length=100)),
                ('feature_2_description', models.TextField(blank=True)),
                ('feature_2_icon', models.CharField(blank=True, max_length=50)),
                ('feature_3_title', models.CharField(blank=True, max_length=100)),
                ('feature_3_description', models.TextField(blank=True)),
                ('feature_3_icon', models.CharField(blank=True, max_length=50)),
                ('enable_newsletter', models.BooleanField(default=True)),
                ('enable_contact_form', models.BooleanField(default=True)),
                ('footer_text', models.TextField(blank=True, help_text='Footer copyright or additional text')),
                ('is_active', models.BooleanField(default=True)),
                ('show_menu_online', models.BooleanField(default=True)),
                ('show_reservations_online', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_data', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Website Data',
                'verbose_name_plural': 'Website Data',
            },
        ),
    ]
