# Generated by Django 5.2.10 on 2026-02-02 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_websitedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='🍽️ Bhansa Ghar', max_length=200)),
                ('hero_subtitle', models.CharField(default='Discover delicious food from multiple restaurants', max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='landing_page/')),
                ('hero_cta_text', models.CharField(default='Browse Restaurants', max_length=100)),
                ('hero_cta_link', models.CharField(default='#restaurants', max_length=200)),
                ('info_banner_text', models.TextField(default="📍 How it works: Browse any restaurant's menu → Scan the QR code on your table → Place your order instantly!")),
                ('info_banner_icon', models.CharField(default='📍', max_length=50)),
                ('feature_1_title', models.CharField(default='Multiple Restaurants', max_length=100)),
                ('feature_1_description', models.TextField(default='Access menus from various restaurants')),
                ('feature_1_icon', models.CharField(default='🏪', max_length=50)),
                ('feature_2_title', models.CharField(default='Quick Ordering', max_length=100)),
                ('feature_2_description', models.TextField(default='Fast and easy order placement')),
                ('feature_2_icon', models.CharField(default='⚡', max_length=50)),
                ('feature_3_title', models.CharField(default='Table QR Code', max_length=100)),
                ('feature_3_description', models.TextField(default='Scan and order directly from your table')),
                ('feature_3_icon', models.CharField(default='📱', max_length=50)),
                ('cta_title', models.CharField(default='Ready to Order?', max_length=200)),
                ('cta_description', models.TextField(default='Select a restaurant and start browsing their menu')),
                ('cta_button_text', models.CharField(default='View All Restaurants', max_length=100)),
                ('footer_text', models.TextField(default='© 2026 Bhansa Ghar - Digital Dining Experience | All Rights Reserved')),
                ('footer_links_visible', models.BooleanField(default=True, help_text='Show footer links section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing Page Content',
                'verbose_name_plural': 'Landing Page Content',
                'permissions': [('can_edit_landing_page', 'Can edit landing page content')],
            },
        ),
    ]
