# Generated by Django 5.2.10 on 2026-02-02 17:38

import core.services.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_landingpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='about_description',
            field=models.TextField(default='We are revolutionizing the dining experience.'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='about_description_2',
            field=models.TextField(blank=True, default='Our platform connects you with the best local flavors.'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='about_image',
            field=models.ImageField(blank=True, help_text='About section image (800x600 recommended)', null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to='bhansa_ghar_landing_page/'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='about_title',
            field=models.CharField(default='About Us', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='app_section_description',
            field=models.TextField(default='Download our mobile app for better experience'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='app_section_title',
            field=models.CharField(default='Get the App', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='brand_name',
            field=models.CharField(default='Bhansa Ghar', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='features_subtitle',
            field=models.TextField(default='Experience the future of dining with our innovative platform'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='features_title',
            field=models.CharField(default='Why Choose Us', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='footer_section_for_restaurants_title',
            field=models.CharField(default='For Restaurants', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='footer_section_quick_links_title',
            field=models.CharField(default='Quick Links', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='footer_section_support_title',
            field=models.CharField(default='Support', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='footer_tagline',
            field=models.CharField(default='Making food ordering simple and enjoyable', max_length=300),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='highlight_1',
            field=models.CharField(default='Fresh Ingredients', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='highlight_2',
            field=models.CharField(default='Best Chefs', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='highlight_3',
            field=models.CharField(default='Fast Delivery', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='highlight_4',
            field=models.CharField(default='User Friendly', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='logo',
            field=models.CharField(default='🍽️', help_text='Emoji logo or text icon', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='restaurants_count_label',
            field=models.CharField(default='Partner Restaurants', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='restaurants_section_subtitle',
            field=models.TextField(default='Explore a wide variety of cuisines from our top-rated partners'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='restaurants_section_tag',
            field=models.CharField(default='Our Partners', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='restaurants_section_title',
            field=models.CharField(default='Choose Your Restaurant', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='stat_2_label',
            field=models.CharField(default='Daily Orders', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='stat_2_value',
            field=models.CharField(default='500+', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='stat_3_label',
            field=models.CharField(default='Happy Customers', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='stat_3_value',
            field=models.CharField(default='1000+', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='stat_4_label',
            field=models.CharField(default='Support', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='stat_4_value',
            field=models.CharField(default='24/7', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Main banner image (1920x1080 recommended)', null=True, storage=core.services.storage.OptimizedCloudinaryStorage(), upload_to='bhansa_ghar_landing_page/'),
        ),
    ]
