# Generated by Django 5.2.10 on 2026-02-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_landingpagecontent_about_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPageContent',
        ),
    ]
