# Generated by Django 5.2.10 on 2026-01-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_e89e13_idx',
            old_name='notifications_user_id_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_fc4790_idx',
            old_name='notifications_user_id_read_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_6027fd_idx',
            old_name='notifications_user_id_category_timestamp_idx',
        ),
    ]
